### PR TITLE
Support for RoboVM 1.5.0

### PR DESCRIPTION
**Pull request by zikolach**

### CODE REVIEW

**Comment by Darkyenus** [comment]
Whoa. Just a note that this doesn't just update to 1.5.0, it also does a quite lot of (breaking) changes.

**Comment by zikolach** [comment]
Yes, and there is an issue in examples with NoClassDefFound for StdIn.
Would be nice to fix it, because 1.0.0-alpha seems a bit outdated :(

**Comment by Darkyenus** [comment]
Where is the issue, here or in my fork? (I have also forked the examples)

**Comment by zikolach** [comment]
I just forked both your repos - sbt robovm plugin and examples. When I updated versions I noticed a bug in native example. I didn't check what caused issue with StdIn yet.

**Comment by Darkyenus** [comment]
Please report any bugs you find to the respective repo, I'll try to fix them.

**Comment by pocorall** [comment]
@ajhager seems very busy to review this awesome pull request. Definately, this should be merged to mainstream.

**Comment by Darkyenus** [comment]
Wow, I didn't think that this would get merged. In this case, there will have to be a few changes, mainly (and maybe only) in README, since I have put some my-fork-specific info there. I think I can provide PR for that after the weekend. In any case, are you planning to publish to plugin repo?

**Comment by pocorall** [comment]
I don't have a permission to access the plugin repo. Some days ago, I just requested to @ajhager for becoming a committer of this git repo.

**Comment by Darkyenus** [comment]
Oh, okay then

**Comment by ajhager** [comment]
My apologies, I have been in the process of changing jobs (RoboVM actually!), getting married, and have just moved across the country. Thanks @Darkyenus for the PR and @pocorall for handling the merge. I agree we need a better protocol for doing plugin releases, and I want to make sure that I am not the weak link for updates and releases. I have broken this discussion off to #35, so feel free to respond.

**Comment by pocorall** [comment]
Congratulations! you got a great job. More congratulations on your marriage!

**Pull request merged**
